# Evaluation notebook
This notebook is meant to be executed after 'main.py'. The results obtained are here reported and displayed.

The first cell contains the parameters to be tuned for a correct execution.

In [1]:
datapath = "./data/results/"
subjects = [1,2,23]
model_names = ["Convolutional", "Convolutional1DRecurrent"]

In [2]:
from numpy import loadtxt, zeros

## Task A

In [3]:
task = "A"
results = zeros([3,len(subjects),len(model_names)])
print(results.shape)

(3, 2, 2)


In [4]:
for model in enumerate(model_names):
    for s in enumerate(subjects):
        filename = task + "_" + model[1] + "_" + str(s[1]) + ".txt"
        print("Loading", filename)
        results[:,s[0], model[0]] = loadtxt(datapath + filename, comments="#", delimiter="\n", unpack=False)

Loading A_Convolutional_1.txt
Loading A_Convolutional_2.txt
Loading A_Convolutional1DRecurrent_1.txt
Loading A_Convolutional1DRecurrent_2.txt


In [5]:
results

array([[[0.9009, 0.8943],
        [0.8277, 0.7461]],

       [[0.949 , 0.9603],
        [0.9506, 0.9432]],

       [[0.9445, 0.9338],
        [0.7799, 0.779 ]]])

### Results for classification with null class
These results consist of the ones of One-Shot classification, which are stored on the top matrix.

In [6]:
results[0,:,:]

array([[0.9009, 0.8943],
       [0.8277, 0.7461]])

### Results for classification without null class
These results consist of the ones of Two-Steps classification, which are stored on the bottom matrix.

In [7]:
results[2,:,:]

array([[0.9445, 0.9338],
       [0.7799, 0.779 ]])